// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxwrarlkglafqqshrkub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4d3JhcmxrZ2xhZnFxc2hya3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDY4MTIsImV4cCI6MjA3MjkyMjgxMn0.i2DlqlADEhA8iw30CCToflLKyTwdyfH4Am-Jsda-Z-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});